import{a as u,s as b,i as n}from"./assets/vendor-CqsEcRFW.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function i(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(r){if(r.ep)return;r.ep=!0;const a=i(r);fetch(r.href,a)}})();const e={form:document.querySelector(".js-search-form"),gallery:document.querySelector(".js-gallery"),input:document.querySelector(".js-search-input"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".js-load-more-btn")};u.defaults.baseURL="https://pixabay.com/api";const v="45493659-807fc3e2fcb62ed82bdbe6cc7";async function g({q:t,page:o=1,per_page:i}={}){return(await u.get("/",{params:{key:v,q:encodeURIComponent(t),image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i}})).data}function f(t){return t.map(({webformatURL:o,largeImageURL:i,tags:d,likes:r,views:a,comments:l,downloads:y})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${o}" alt="${d}" width="360" height="152" />
            <ul class="description">
              <li class="description-items">
                <span class="accent">Likes </span>${r}
              </li>
              <li class="description-items">
                <span class="accent">Views </span>${a}
              </li>
              <li class="description-items">
                <span class="accent">Comments </span>${l}
              </li>
              <li class="description-items">
                <span class="accent">Downloads </span>${y}
              </li>
            </ul>
          </a>
        </li>`).join("")}function m(t){t.classList.remove("hidden")}function c(t){t.classList.add("hidden")}const h=new b(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),s={q:"",page:1,per_page:15,total_pages:0};e.form.addEventListener("submit",C);async function C(t){if(t.preventDefault(),e.gallery.innerHTML="",s.page=1,e.loadMoreBtn.removeEventListener("click",p),c(e.loadMoreBtn),s.q=e.input.value.trim(),s.q==="")return n.error({message:"Search field can not be empty!",position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"});m(e.loader);try{const o=await g(s);o.hits.length===0?(e.input.value="",n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})):(s.total_pages=Math.ceil(o.totalHits/s.per_page),s.total_pages>1?(m(e.loadMoreBtn),e.loadMoreBtn.addEventListener("click",p)):(c(e.loadMoreBtn),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3,maxWidth:"432px"}),e.loadMoreBtn.removeEventListener("click",p)),e.input.value="",e.gallery.innerHTML=f(o.hits),h.refresh())}catch(o){n.error({message:`Something went wrong... Error: ${o}`,position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})}finally{c(e.loader)}}async function p(){m(e.loader),s.page+=1,c(e.loadMoreBtn);try{const t=await g(s);e.gallery.insertAdjacentHTML("beforeend",f(t.hits)),h.refresh();const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}catch(t){n.error({message:`Something went wrong... Error: ${t}`,position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})}finally{c(e.loader),s.page===s.total_pages?(e.loadMoreBtn.removeEventListener("click",p),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3,maxWidth:"432px"})):m(e.loadMoreBtn)}}
//# sourceMappingURL=index.js.map
